### ISSUE TITLE
Set up development environment

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#1]
- Configure linter.
- Configure build automation / Maven.
- Configure test runner.
- Set up Continuous Integration
- Etc.

**Comment by sdsantos** [comment]
My task list:
- [ ] Create project
- [ ] Base architecture
- [ ] Setup lint
- [ ] Setup testing
- [ ] Setup Continuous Integration

**Comment by gnarea** [comment]
Re:

- Lint: We're using ktlint via the Spotless Gradle plugin in the JVM library. I'm happy to use something else -- We'd just have to change the JVM library to make sure the dev stack is consistent across all Kotlin/Android repos.
- Testing: We're using JUnit5 and JaCoCo in the JVM library (all configured in Gradle), but again I'm happy to change things. I know some people also like to use an assertion library, for example.
- CI: For unit/integration tests, we're using GitHub Actions across all repos so I'd prefer to stick to that. For functional/UI tests, see #7 and #8.
  - Side note: The JVM library will be fully covered with unit tests and it'll also have integration tests, but I think we should be more relaxed with the Android apps. Here I'd be more interested in functional/UI tests than unit tests.

I think there's quite a bit that we'll be able to reuse from the JVM library (including things like [GH actions](https://github.com/relaycorp/relaynet-jvm/tree/master/.github/workflows)) so I wonder whether step 1 should be to port those things, and then you/I can tweak them once they're in this repo. That's something I do when I start working on a new repo and I don't mind doing it.
