### ISSUE TITLE
Data units are slightly unfriendly in older versions of Android

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#110]
I'd expect the following to read "0 B used of 900 MB", as it'd does in newer versions of Android:

![Screenshot_2020-05-29-11-26-34](https://user-images.githubusercontent.com/369863/83252254-d8112e80-a1a2-11ea-9ef7-d1544d8e01cd.png)

That's on a Nexus 4.

**Comment by sdsantos** [comment]
Just checked and we can't configure much in the method we're using. Either we right our own, or keep using what the system gives us. Let me know if it's worth it writing our own.

**Comment by gnarea** [comment]
Thanks for looking into this. I don't think it's worth writing our own implementation, considering that only 10% of Android devices use version 5 and that number is dropping. I'm not sure in which version of Android this was fixed, but it certainly isn't present in Android 8+ (61% market share) anyway.
