### ISSUE TITLE
Self-issue Internet PKI certificate for gRPC server

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#36]
Requirements:

- Use RSA 2048 + SHA-256.
- `subjectAltName` extension set to the IP address `192.168.0.1` (@sdsantos: is it safe to hard code this value? or can this IP address be different?)
- `basicConstraints` extension should mark the subject as not a CA.
- Expiry date should be short-lived -- In the order of days or weeks. This means the certificate and its key pair should be regenerated periodically.

**Comment by sdsantos** [comment]
I believe the IP address can be different, but we can still lock it, as long as the client disables hostname checks. For example, the Android hotspot is always giving the IP `192.168.43.1` to the device.

**Comment by gnarea** [comment]
Cool, so I'll hard code `192.168.43.1` when generating the cert.
