### ISSUE TITLE
Sync with people breaks when WiFi hostpot is turned off and then back on

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#79]
If you (accidentally) turn off WiFi hostpot during a syncronisation with people and then turn it back on, private gateways won't be able to connect to the courier until the courier manually restarts the synchronisation.

This happens because the courier app will get a new IP address in its `192.168.43.0/24` subnet and it won't match the one for which the current TLS certificate was issue. This isn't a problem on old phones where the IP address is fixed (`192.168.43.1`) but it's problematic in newer versions of Android.

This happened to me when I accidentally turned off WiFi hotspot and I couldn't figure out why things stopped working. I think this will be particularly puzzling for real couriers who won't know about the inner workings of this app.

I think an easy fix could be to stop the synchronisation with people as soon as WiFi hotspot is turned off and present this screen:
![hotspot-disabled](https://user-images.githubusercontent.com/369863/82730276-6181b600-9cf6-11ea-8e6b-8beb76e716fc.png)

Thoughts?

**Comment by sdsantos** [comment]
Yup, we can continue listening to the wifi hotspot state, and stop the server if it was disabled. We can either change to the error state we have on the sync, or go back to that screen. Not sure what's more clear though.

**Comment by gnarea** [comment]
Indeed, I didn't think of the error state. I guess the advantage of using that state is that we'd be explicit as to why the synchronisation stopped.

However, I think the WiFi hotspot screen is friendlier and more helpful in this case: It's giving the user the open to re-enable the hotspot and it isn't saying to the user that they did something wrong (even though they did).

I do agree there's something to be said for being explicit and saying why they're seeing the hostpot screen, but I wonder whether that can be achieved with a different copy. For example, the paragraph below "WiFi hotspot is disabled" could read "WiFi hotspot should stay enabled throughout the synchronization with people" -- And we could replicate the same copy in the hotspot enabled screen too.

Wdyt?

**Comment by sdsantos** [comment]
Ok, I'll go with the "should stay enable" copy.
